server:
 port: 8080
 servlet:
  context-path: /campmail  
  
 spring:  
   devtools:
    restart:
      exclude: logs/**      
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2;
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      show-sql: true      


